app1/urls.py
from django.conf.urls import url
from .import views


app_name = "app1"
urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^course/$', views.course, name="course"),
    url(r'^add_course/$', views.add_course, name="add_course"),
    url(r'^student_reg/$', views.student_reg, name="student_reg"),
    url(r'^staff_reg/$', views.staff_reg, name="staff_reg"),
    url(r'^course_list/$', views.course_list, name="course_list"),
    url(r'^(?P<course_id>[0-9]+)/student_list/$', views.student_list, name="student_list"),
    url(r'^staff_course/$', views.staff_course, name="staff_course"),
    url(r'^(?P<course_id>[0-9]+)/staff_list/$', views.staff_list, name="staff_list"),
    url(r'^(?P<student_id>[0-9]+)/student_details/$', views.student_details, name="student_details"),
    url(r'^(?P<staff_id>[0-9]+)/staff_details/$', views.staff_details, name="staff_details"),
    url(r'^(?P<student_id>[0-9]+)/student_update/$', views.student_update, name="student_update"),

    ]

institute/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^institute/', include('app1.urls')),
    url(r'^admin/', admin.site.urls),
]

app1/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=50)
    course_duration = models.TextField()
    time = models.TimeField(auto_now=False, auto_now_add=False)
    fee = models.IntegerField()


    def __str__(self):
        return self.name


class Student(models.Model):
    course = models.ManyToManyField(Course)
    name = models.CharField(max_length=30)
    email = models.EmailField()
    qualification = models.CharField(max_length=15)
    mobile = models.CharField(max_length=15, blank=True, default=None)
    batch = models.CharField(max_length=30, blank=True, default=None)
    status = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Staff(models.Model):
    name = models.CharField(max_length=100)
    exp = models.CharField(max_length=10, blank=True, default=None)
    salary = models.IntegerField()
    course = models.ManyToManyField(Course)

    def __str__(self):
        return self.name

app1/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from .models import Course, Student, Staff
from django .http import HttpResponseRedirect
from django.shortcuts import reverse
from django.http import HttpResponse
from django.shortcuts import render,  get_object_or_404


def home(request):
    """

    :param request: request form the user to create home page
    :return:if created page will goes to home.html and display
    """

    return render(request, "app1/home.html", {})


def course(request):
    """

    :param request: request form the user to create course id
    :return:if id is created page will goes to course.html and display
    """
    course_list = Course.objects.order_by('id')
    return render(request, "app1/course.html", {"course_list": course_list})


def add_course(request):
    """
    :param request:request from the user to create
    :return:if form is valid page will  redirected to course,
    in case form is not valid  page will goes to add_course html and display
    """
    if request.method == 'POST':
        Course.objects.create(name=request.POST['name'],
                              course_duration=request.POST['course_duration'],
                              time=request.POST['time'],
                              fee=request.POST['fee'])

        return HttpResponseRedirect(reverse("app1:course"))
    return render(request, "app1/add_course.html", {})


def student_reg(request):

    """

    :param request:request from the user to create
    :return:if form is valid page will  response to sucess,
    in case form is not valid  page will goes to student_reg html and display
    """
    if request.method == 'POST':
        print request.POST["team"]
        # if request method is post then get the course id
        cr = Course.objects.get(pk=request.POST['team'])

        st = Student.objects.create(name=request.POST['name'],
                                    email=request.POST['email'],
                                    qualification=request.POST['qualification'],
                                    mobile=request.POST['mobile'],
                                    batch=request.POST['batch'],
                                    status=request.POST['status']
                                    )
        # if create the student id then get student.id
        st1 = Student.objects.get(pk=st.id)
        # course should be include in the student
        st1.course.add(cr)
        st1.save()
        return HttpResponse("sucess")

    else:
        course = Course.objects.all()
        return render(request, "app1/student_reg.html", {"course": course})


def staff_reg(request):

    """

    :param request:request from the user to create
    :return:if form is valid page will  response to sucess,
    in case form is not valid  page will goes to staff_reg html and display
    """
    if request.method == 'POST':
        print request.POST["team"]
        # if request method is post then get the course id
        cr = Course.objects.get(pk=request.POST['team'])
        stf = Staff.objects.create(name=request.POST['name'],
                                   exp=request.POST['exp'],
                                   salary=request.POST['salary'])
        # if create the staff id then get staff.id
        st2 = Staff.objects.get(pk=stf.id)
        # course should be include in the staff
        st2.course.add(cr)
        st2.save()
        return HttpResponse("sucess")

    else:
        course=Course.objects.all()
        return render(request, "app1/staff_reg.html", {"course": course})


def course_list(request):
    """

    :param request:
    :return:
    """
    student = Student.objects.all()
    l = []
    for s in student:
        for j in s.course.all():
            l.append(j)

    l = set(l)
    return render(request, 'app1/course_list.html', {'courselist': l})


def student_list(request, course_id):
    """

    :param request:
    :param course_id:
    :return:
    """
    # import pdb
    # pdb.set_trace()
    c = Course.objects.get(pk=course_id)
    student_list = c.student_set.all()

    staff_list = c.staff_set.all()
    students = c.student_set.all()
    return render(request, "app1/student_display.html", {"student_list": student_list, "staff_list": staff_list,"students": students})


def staff_course(request):
    """

    :param request:
    :return:
    """
    staff = Staff.objects.all()
    a = []
    for t in staff:
        for k in t.course.all():
            a.append(k)

    a = set(a)
    return render(request, 'app1/staff_course.html', {'staffcourse': a})


def staff_list(request, course_id):
    """

    :param request:request from the to get the course.id
    :param course_id:if the staff_id get
    :return: get the course id and display the staff name in the course staff
    """
    cf = Course.objects.get(pk=course_id)
    staff_list = cf.staff_set.all()
    return render(request, "app1/staff_display.html", {"staff_list": staff_list})


def student_details(request, student_id):
    """

    :param request:request from the user to detail student
    :param student_id:if the student_id created
    :return:if student.id is created then display the all student details page will be goes to the
    student_details.html
    """

    student = Student.objects.get(id=student_id)
    return render(request, "app1/student_details.html", {"student": student})


def staff_details(request, staff_id):
    """

    :param request:request from the user to detail staff
    :param staff_id:if the staff_id created
    :return:if staff details will display the page will be goes to
    the staff_details.html
    """
    staff = Staff.objects.get(id=staff_id)
    return render(request, "app1/staff_details.html", {"staff": staff})


def student_update(request, student_id):
    """

    :param request:request from the user to update
    :param student_id: update student status
    :return: if update is valid page will be redirect to student_details.html,
     in case  not valid  page will goes to update. html and display

    """
    if request.method == "POST":
        # you need to filter student id and update the status in student
        Student.objects.filter(pk=student_id).update(status=request.POST['status'])
        # student = Student.objects.get(pk=student_id)
        # student.status=request.POST['status']
        # student.save()
        return HttpResponseRedirect(reverse('app1:student_details', args=student_id))
    return render(request, "app1/update.html", {})

app1/templates/app1/add_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="." method="post" enctype="multipart/form-data"><br>
    {% csrf_token %}
        name: <input type="text" name="name" ><br>
        course duration: <input type="text" name="course_duration" ><br>
       time: <input type="text" name="time" ><br>
       fee: <input type="text" name="fee" ><br>
    <input type="submit" value="create">
    </form>

</body>
</html>

app1/templates/app1/course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-color:powderblue;">
{% if course_list %}

{% for course in course_list %}
<h4>{{course.name}}</h4>
{% endfor %}

{% endif %}
<a href="{%url 'app1:add_course'  %}">add</a>
<a href="/institute/">back</a>

</body>
</html>

app1/templates/app1/course_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-color:powderblue;">
<center><h3>STUDENT COURSE NAME</h3></center><br>
{% for course in courselist %}
<center><a href="{%url 'app1:student_list' course.id %}">{{course.name}}</a></center><br>
{% endfor %}
<a href="/institute/">back</a>

</body>
</html>

app1/templates/app1/home.html
<!DOCTYPE html>
<html lang="en">
<head>
     <center> <h1>WELCOME TO MAIN PAGE</h1></center>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-color:powderblue;">
<h3><a href="{%url 'app1:student_reg' %}">Student Registration</a></h3>
<h3><a href="{%url 'app1:staff_reg' %}">Staff Registration</a></h3>
<h3><a href="{%url 'app1:course_list'  %}">Student list</a></h3>
<h3><a href="{%url 'app1:staff_course'  %}">Staff list</a></h3>


<h2><a href="{%url 'app1:course'  %}">courses</a></h2>

</body>
</html>

app1/templates/app1/staff_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-color:powderblue;">
<center><h3>STAFF COURSE NAME</h3></center>
{% for course in staffcourse %}
<center><a href="{%url 'app1:staff_list' course.id %}">{{course.name}}</a></center><br>
{% endfor %}
<a href="/institute/">back</a>

</body>
</html>

app1/templates/app1/staff_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>staff details page</title>
</head>
<body>
Name :{{staff.name}}<br>
Exp :{{staff.exp}}<br>
salary :{{staff.salary}}<br>


</body>
</html>

app1/templates/app1/staff_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<center>STAFF NAME</center>
{% for staff in staff_list %}
   {{staff}}<br>
{% endfor %}


</body>
</html>

app1/templates/app1/staff_reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<center>STAFF REGISTRATION</center>
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
         name: <input type="text" name=" name" ><br>
         exp: <input type="text" name=" exp"><br>
         salary: <input type="text" name=" salary" ><br>
         course:
       <select name="team">
           <option selected="selected" disabled>object on page</option><br>
           {% for team in course %}
        <option value="{{team.id}}">{{team.name}}</option>
           {% endfor %}
    </select>


     <br><input type="submit" value="save "/><br>
    <a href="/institute/">back</a>


</form>


</body>
</html>

app1/templates/app1/student_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Name :{{student.name}}<br>
Email :{{student.email}}<br>
qualification :{{student.qualification}}<br>
Mobile :{{student.mobile}}<br>
Batch :{{student.batch}}<br>
Status :{{student.status}}<br>
<a href="{%url 'app1:student_update' student.id  %}">update</a>

<br><a href="/institute">back</a>




</body>
</html>

app1/templates/app1/student_display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table style="width:40%">
  <tr>
    <th>Student</th>
    <th>Staff</th>
    <th>Batch</th>
      <th>time</th>
      <th>paid</th>
  </tr>
    <tr>

            {% for each in student_list %}
            <td><a href="{%url 'app1:student_details' each.id %}">{{each}}</a></td>
         {% endfor %}


        {% for ea in staff_list %}
        <td><a href="{%url 'app1:staff_details' ea.id %}">{{ea}}</a></td>
         {% endfor %}


        {% for student in students %}
        <td>{{student.batch}}</td>
        {% endfor %}

        {% for c in course %}
           {{c.time}}
        {% endfor %}

  </tr>


</table>
</body>
</html>

app1/templates/app1/student_reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<center>STUDENT REGISTRATION</center>
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
         name: <input type="text" name=" name" ><br>
         email: <input type="text" name=" email"><br>
         qualification: <input type="text" name=" qualification" ><br>
        mobile: <input type="text" name=" mobile" ><br>
        Batch: <input type="text" name=" batch" ><br>
        status: <input type="text" name=" status" ><br>
        course:<br>
    {% for team in course %}
        &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;
<!--    <select name="course">-->
<!--        <option value="{{ team.id }}">{{team.name}}</option>-->
<!--    </select>-->
    <input type="radio" name="team"  value="{{ team.id }} " />
    {{team.name}} <br />
    {% endfor %}

     <input type="submit" value="save "/><br>
    <a href="/institute/">back</a>


</form>

</body>
</html>

app1/templates/app1/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
         status: <input type="text" name= "status" ><br>

    <input type="submit" value="save"/>
</form>
</body>
</html>

<a href="/institute/">back</a>